// GENERATED FILE — do not edit by hand. Run: npm run fetch-gemara-perakim
// Where every perek of the Babylonian Talmud begins, in the order the perakim
// are printed in the masechet (which is not always the Mishnah's chapter order).
//
// Derived from Sefaria's "Mishnah Map.csv" in github.com/Sefaria/Sefaria-Project,
// cached at tools/perakim-cache/mishnah-map.csv, and cross-checked against the
// bundled text: 313 perakim across 37 tractates, 215 of
// the boundaries also confirmed by a "הדרן עלך" marker in the text itself.

export interface GemaraPerek {
	perek: number;
	daf: string;
}

/** tractate -> its perakim in printed order, each with the daf it opens on. */
export const GEMARA_PERAKIM: Record<string, GemaraPerek[]> = {
	"Arakhin": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "7b" },
		{ perek: 3, daf: "13b" },
		{ perek: 4, daf: "17a" },
		{ perek: 5, daf: "19a" },
		{ perek: 6, daf: "21b" },
		{ perek: 7, daf: "24a" },
		{ perek: 8, daf: "27a" },
		{ perek: 9, daf: "29b" },
	],
	"Avodah Zarah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "22a" },
		{ perek: 3, daf: "40b" },
		{ perek: 4, daf: "49b" },
		{ perek: 5, daf: "62a" },
	],
	"Bava Batra": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "17a" },
		{ perek: 3, daf: "28a" },
		{ perek: 4, daf: "61a" },
		{ perek: 5, daf: "73a" },
		{ perek: 6, daf: "92a" },
		{ perek: 7, daf: "102b" },
		{ perek: 8, daf: "108a" },
		{ perek: 9, daf: "139b" },
		{ perek: 10, daf: "160a" },
	],
	"Bava Kamma": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "17a" },
		{ perek: 3, daf: "27a" },
		{ perek: 4, daf: "36a" },
		{ perek: 5, daf: "46a" },
		{ perek: 6, daf: "55b" },
		{ perek: 7, daf: "62b" },
		{ perek: 8, daf: "83b" },
		{ perek: 9, daf: "93b" },
		{ perek: 10, daf: "111b" },
	],
	"Bava Metzia": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "21a" },
		{ perek: 3, daf: "33b" },
		{ perek: 4, daf: "44a" },
		{ perek: 5, daf: "60b" },
		{ perek: 6, daf: "75b" },
		{ perek: 7, daf: "83a" },
		{ perek: 8, daf: "94a" },
		{ perek: 9, daf: "103a" },
		{ perek: 10, daf: "116b" },
	],
	"Beitzah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "15b" },
		{ perek: 3, daf: "23b" },
		{ perek: 4, daf: "29b" },
		{ perek: 5, daf: "35b" },
	],
	"Bekhorot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "13a" },
		{ perek: 3, daf: "19b" },
		{ perek: 4, daf: "26b" },
		{ perek: 5, daf: "31a" },
		{ perek: 6, daf: "37a" },
		{ perek: 7, daf: "43a" },
		{ perek: 8, daf: "46a" },
		{ perek: 9, daf: "53a" },
	],
	"Berakhot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "13a" },
		{ perek: 3, daf: "17b" },
		{ perek: 4, daf: "26a" },
		{ perek: 5, daf: "30b" },
		{ perek: 6, daf: "35a" },
		{ perek: 7, daf: "45a" },
		{ perek: 8, daf: "51b" },
		{ perek: 9, daf: "54a" },
	],
	"Chagigah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "11b" },
		{ perek: 3, daf: "20b" },
	],
	"Chullin": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "27a" },
		{ perek: 3, daf: "42a" },
		{ perek: 4, daf: "68a" },
		{ perek: 5, daf: "78a" },
		{ perek: 6, daf: "83b" },
		{ perek: 7, daf: "89b" },
		{ perek: 8, daf: "103b" },
		{ perek: 9, daf: "117b" },
		{ perek: 10, daf: "130a" },
		{ perek: 11, daf: "135a" },
		{ perek: 12, daf: "138b" },
	],
	"Eruvin": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "17b" },
		{ perek: 3, daf: "26b" },
		{ perek: 4, daf: "41b" },
		{ perek: 5, daf: "52b" },
		{ perek: 6, daf: "61b" },
		{ perek: 7, daf: "76a" },
		{ perek: 8, daf: "82a" },
		{ perek: 9, daf: "89a" },
		{ perek: 10, daf: "95a" },
	],
	"Gittin": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "15a" },
		{ perek: 3, daf: "24a" },
		{ perek: 4, daf: "32a" },
		{ perek: 5, daf: "48b" },
		{ perek: 6, daf: "62b" },
		{ perek: 7, daf: "67b" },
		{ perek: 8, daf: "77a" },
		{ perek: 9, daf: "82a" },
	],
	"Horayot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "6b" },
		{ perek: 3, daf: "9b" },
	],
	"Keritot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "8b" },
		{ perek: 3, daf: "11b" },
		{ perek: 4, daf: "17a" },
		{ perek: 5, daf: "20b" },
		{ perek: 6, daf: "23b" },
	],
	"Ketubot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "15b" },
		{ perek: 3, daf: "29a" },
		{ perek: 4, daf: "41b" },
		{ perek: 5, daf: "54b" },
		{ perek: 6, daf: "65b" },
		{ perek: 7, daf: "70a" },
		{ perek: 8, daf: "78a" },
		{ perek: 9, daf: "83a" },
		{ perek: 10, daf: "90a" },
		{ perek: 11, daf: "95b" },
		{ perek: 12, daf: "101b" },
		{ perek: 13, daf: "104b" },
	],
	"Kiddushin": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "41a" },
		{ perek: 3, daf: "58b" },
		{ perek: 4, daf: "69a" },
	],
	"Makkot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "7a" },
		{ perek: 3, daf: "13a" },
	],
	"Megillah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "17a" },
		{ perek: 3, daf: "21a" },
		{ perek: 4, daf: "25b" },
	],
	"Meilah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "8a" },
		{ perek: 3, daf: "10b" },
		{ perek: 4, daf: "15a" },
		{ perek: 5, daf: "18a" },
		{ perek: 6, daf: "20a" },
	],
	"Menachot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "13a" },
		{ perek: 3, daf: "17a" },
		{ perek: 4, daf: "38a" },
		{ perek: 5, daf: "52b" },
		{ perek: 6, daf: "63b" },
		{ perek: 7, daf: "72b" },
		{ perek: 8, daf: "76b" },
		{ perek: 9, daf: "83b" },
		{ perek: 10, daf: "87a" },
		{ perek: 11, daf: "94a" },
		{ perek: 12, daf: "100b" },
		{ perek: 13, daf: "104b" },
	],
	"Moed Katan": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "11b" },
		{ perek: 3, daf: "13b" },
	],
	"Nazir": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "9a" },
		{ perek: 3, daf: "16a" },
		{ perek: 4, daf: "20b" },
		{ perek: 5, daf: "30b" },
		{ perek: 6, daf: "34a" },
		{ perek: 7, daf: "47a" },
		{ perek: 8, daf: "57a" },
		{ perek: 9, daf: "61a" },
	],
	"Nedarim": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "13b" },
		{ perek: 3, daf: "20b" },
		{ perek: 4, daf: "32b" },
		{ perek: 5, daf: "45b" },
		{ perek: 6, daf: "49a" },
		{ perek: 7, daf: "54a" },
		{ perek: 8, daf: "60a" },
		{ perek: 9, daf: "64a" },
		{ perek: 10, daf: "66b" },
		{ perek: 11, daf: "79a" },
	],
	"Niddah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "13a" },
		{ perek: 3, daf: "21a" },
		{ perek: 4, daf: "31b" },
		{ perek: 5, daf: "40a" },
		{ perek: 6, daf: "48a" },
		{ perek: 7, daf: "54b" },
		{ perek: 8, daf: "57b" },
		{ perek: 9, daf: "59b" },
		{ perek: 10, daf: "64b" },
	],
	"Pesachim": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "21a" },
		{ perek: 3, daf: "42a" },
		{ perek: 4, daf: "50a" },
		{ perek: 5, daf: "58a" },
		{ perek: 6, daf: "65b" },
		{ perek: 7, daf: "74a" },
		{ perek: 8, daf: "87a" },
		{ perek: 9, daf: "92b" },
		{ perek: 10, daf: "99b" },
	],
	"Rosh Hashanah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "22a" },
		{ perek: 3, daf: "25b" },
		{ perek: 4, daf: "29b" },
	],
	"Sanhedrin": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "18a" },
		{ perek: 3, daf: "23a" },
		{ perek: 4, daf: "32a" },
		{ perek: 5, daf: "40a" },
		{ perek: 6, daf: "42b" },
		{ perek: 7, daf: "49b" },
		{ perek: 8, daf: "68b" },
		{ perek: 9, daf: "75a" },
		{ perek: 10, daf: "84b" },
		{ perek: 11, daf: "90a" },
	],
	"Shabbat": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "20b" },
		{ perek: 3, daf: "36b" },
		{ perek: 4, daf: "47b" },
		{ perek: 5, daf: "51b" },
		{ perek: 6, daf: "57a" },
		{ perek: 7, daf: "67b" },
		{ perek: 8, daf: "76b" },
		{ perek: 9, daf: "82a" },
		{ perek: 10, daf: "90b" },
		{ perek: 11, daf: "96a" },
		{ perek: 12, daf: "102b" },
		{ perek: 13, daf: "105a" },
		{ perek: 14, daf: "107a" },
		{ perek: 15, daf: "111b" },
		{ perek: 16, daf: "115a" },
		{ perek: 17, daf: "122b" },
		{ perek: 18, daf: "126b" },
		{ perek: 19, daf: "130a" },
		{ perek: 20, daf: "137b" },
		{ perek: 21, daf: "141b" },
		{ perek: 22, daf: "143b" },
		{ perek: 23, daf: "148a" },
		{ perek: 24, daf: "153a" },
	],
	"Shevuot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "14a" },
		{ perek: 3, daf: "19b" },
		{ perek: 4, daf: "30a" },
		{ perek: 5, daf: "36b" },
		{ perek: 6, daf: "38b" },
		{ perek: 7, daf: "44b" },
		{ perek: 8, daf: "49a" },
	],
	"Sotah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "14a" },
		{ perek: 3, daf: "19a" },
		{ perek: 4, daf: "23b" },
		{ perek: 5, daf: "27b" },
		{ perek: 6, daf: "31a" },
		{ perek: 7, daf: "32a" },
		{ perek: 8, daf: "42a" },
		{ perek: 9, daf: "44b" },
	],
	"Sukkah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "20b" },
		{ perek: 3, daf: "29b" },
		{ perek: 4, daf: "42b" },
		{ perek: 5, daf: "50a" },
	],
	"Taanit": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "15a" },
		{ perek: 3, daf: "18b" },
		{ perek: 4, daf: "26a" },
	],
	"Tamid": [
		{ perek: 1, daf: "25b" },
		{ perek: 2, daf: "28b" },
		{ perek: 3, daf: "30a" },
		{ perek: 4, daf: "30b" },
		{ perek: 5, daf: "32b" },
		{ perek: 6, daf: "33a" },
		{ perek: 7, daf: "33b" },
	],
	"Temurah": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "14a" },
		{ perek: 3, daf: "17b" },
		{ perek: 4, daf: "21b" },
		{ perek: 5, daf: "24b" },
		{ perek: 6, daf: "28a" },
		{ perek: 7, daf: "31a" },
	],
	"Yevamot": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "17a" },
		{ perek: 3, daf: "26a" },
		{ perek: 4, daf: "35b" },
		{ perek: 5, daf: "50a" },
		{ perek: 6, daf: "53b" },
		{ perek: 7, daf: "66a" },
		{ perek: 8, daf: "70a" },
		{ perek: 9, daf: "84a" },
		{ perek: 10, daf: "87b" },
		{ perek: 11, daf: "97a" },
		{ perek: 12, daf: "101a" },
		{ perek: 13, daf: "107a" },
		{ perek: 14, daf: "112b" },
		{ perek: 15, daf: "114b" },
		{ perek: 16, daf: "119a" },
	],
	"Yoma": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "22a" },
		{ perek: 3, daf: "28a" },
		{ perek: 4, daf: "39a" },
		{ perek: 5, daf: "47a" },
		{ perek: 6, daf: "62a" },
		{ perek: 7, daf: "68b" },
		{ perek: 8, daf: "73b" },
	],
	"Zevachim": [
		{ perek: 1, daf: "2a" },
		{ perek: 2, daf: "15b" },
		{ perek: 3, daf: "31b" },
		{ perek: 4, daf: "36b" },
		{ perek: 5, daf: "47a" },
		{ perek: 6, daf: "58a" },
		{ perek: 7, daf: "66a" },
		{ perek: 8, daf: "70b" },
		{ perek: 9, daf: "83a" },
		{ perek: 10, daf: "89a" },
		{ perek: 11, daf: "92a" },
		{ perek: 12, daf: "98b" },
		{ perek: 13, daf: "106a" },
		{ perek: 14, daf: "112a" },
	],
};
